name: Jekyll site CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Setup Ruby for use with actions
        uses: actions/setup-ruby@v1.0.0
        #with:
          # Version range or exact version of a Ruby version to use.
          #version: # optional, default is >= 2.4
      
      - name: SIMULATOR - Center simulator in page view
        run: sed -i 's/body\ style\=\"/body\ style\=\"text-align\:\ center\;/g' simulations/CoVprehension.html
      
      - name: Install jenkyll plugins
        run: bundle install
        env:
          NOKOGIRI_USE_SYSTEM_LIBRARIES: true

      - name: Build the site 
        run: (timeout 15 bundle exec jekyll serve --trace; exit 0)
        env:
          NOKOGIRI_USE_SYSTEM_LIBRARIES: true

      - name: Upload to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v1.3.0
        with:
          # GitHub repository where assets will be deployed (default current)
          #repo: # optional
          # Git branch where assets will be deployed
          #target_branch: # optional, default is gh-pages
          # Create incremental commit instead of doing push force
          keep_history: true
          # Allow an empty commit to be created
          allow_empty_commit: false
          # Build directory to deploy
          build_dir: _site
          # Commit author's name
          committer_name: Github Actions
          # Commit author's email
          committer_email: actions@github.com
          # Commit message
          #commit_message: # optional
          # Write the given domain name to the CNAME file
          #fqdn: # optional  
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_PAT: ${{ secrets.GITHUB_PAT }}
